version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
      - run: echo -e "Host enjambrelab.com.ar\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run: make deploy
      - run: ls dist/
workflows:
  version: 2
  compilar-y-subir:
    jobs:
      - build
      - deploy:
          filters:
            tags:
              only: /^v\d+.\d+.\d+/
            branches:
              ignore: /.*/
